import { mkdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import { marketIntelligencePackSchema, type MarketIntelligencePack } from "@wow-trader/contracts";

import type { CollectorScan } from "./collector-schema.js";

interface RequestOptions {
  readonly signal?: AbortSignal | undefined;
}

const GENERATED_FILE_NAME = "MarketData.lua";

export async function downloadMarketIntelligence(
  endpoint: URL,
  apiKey: string,
  scan: CollectorScan,
  options: RequestOptions = {},
): Promise<MarketIntelligencePack> {
  const url = new URL("/v1/market-intelligence", endpoint);
  url.search = new URLSearchParams({
    clientProduct: scan.clientProduct,
    clientBuild: String(scan.clientBuild),
    region: scan.region,
    realmId: scan.realmId,
    auctionHouseType: scan.auctionHouseType,
  }).toString();
  const response = await fetch(url, {
    headers: { authorization: `Bearer ${apiKey}` },
    signal: options.signal
      ? AbortSignal.any([options.signal, AbortSignal.timeout(60_000)])
      : AbortSignal.timeout(60_000),
  });
  const body: unknown = await response.json().catch(() => null);
  if (!response.ok) {
    const message = readErrorMessage(body) ?? `HTTP ${response.status}`;
    throw new Error(`Market intelligence download failed: ${message}`);
  }
  return marketIntelligencePackSchema.parse(body);
}

export async function installMarketIntelligence(
  wowProductRoot: string,
  pack: MarketIntelligencePack,
): Promise<string> {
  const addonRoot = path.join(
    path.resolve(wowProductRoot),
    "Interface",
    "AddOns",
    "WowTraderCollector",
  );
  await mkdir(addonRoot, { recursive: true });
  const destination = path.join(addonRoot, GENERATED_FILE_NAME);
  const temporary = path.join(addonRoot, `.${GENERATED_FILE_NAME}.${process.pid}.tmp`);
  await writeFile(temporary, serializeMarketIntelligence(pack), { encoding: "utf8", mode: 0o644 });
  try {
    await rename(temporary, destination);
  } finally {
    await rm(temporary, { force: true });
  }
  return destination;
}

export function serializeMarketIntelligence(pack: MarketIntelligencePack): string {
  const validated = marketIntelligencePackSchema.parse(pack);
  const items = validated.items
    .map(
      (item) => `  [${item.itemId}] = {
    name = ${luaString(item.name)}, signal = ${luaString(item.signal)}, observations = ${item.observationCount}, minimum = ${item.minimumObservationCount},
    current = ${luaString(item.currentPriceCopper)}, normal = ${luaString(item.normalPriceCopper)}, low = ${luaString(item.lowerPriceCopper)}, high = ${luaString(item.upperPriceCopper)},
    differenceBP = ${luaNumber(item.differenceBasisPoints)}, quantity = ${luaNumber(item.currentQuantity)}, normalQuantity = ${luaNumber(item.normalQuantity)}, supplyBP = ${luaNumber(item.supplyRatioBasisPoints)},
    listings = ${luaNumber(item.currentListingCount)}, confidenceBP = ${luaNumber(item.confidenceBasisPoints)}, direction = ${luaString(item.direction)},
  },`,
    )
    .join("\n");
  return `-- Generated by WoW Trader Companion. Do not edit.
WOW_TRADER_MARKET_DATA = {
  schemaVersion = 1,
  modelVersion = ${luaString(validated.modelVersion)},
  clientProduct = ${luaString(validated.clientProduct)},
  clientBuild = ${validated.clientBuild},
  region = ${luaString(validated.region)},
  realmId = ${luaString(validated.realmId)},
  auctionHouseType = ${luaString(validated.auctionHouseType)},
  generatedAt = ${luaString(validated.generatedAt)},
  sourceScanAt = ${luaString(validated.sourceScanAt)},
  items = {
${items}
  },
}
`;
}

function luaString(value: string | null): string {
  if (value === null) return "nil";
  return `"${value
    .replaceAll("\\", "\\\\")
    .replaceAll('"', '\\"')
    .replaceAll("\r", "\\r")
    .replaceAll("\n", "\\n")}"`;
}

function luaNumber(value: number | null): string {
  return value === null ? "nil" : String(value);
}

function readErrorMessage(value: unknown): string | null {
  if (!value || typeof value !== "object" || !("message" in value)) return null;
  return typeof value.message === "string" ? value.message : null;
}
