import type { Metadata } from "next";
import Link from "next/link";

import { DataUnavailable } from "../../../../../components/data-unavailable";
import { ForeverSnapshotNotice } from "../../../../../components/forever-snapshot-notice";
import { getForeverSnapshot } from "../../../../../lib/forever";
import { createHelperMetadata } from "../../../../../lib/seo";

export const dynamic = "force-dynamic";

export const metadata: Metadata = createHelperMetadata({
  title: "Talents Forever Source & Coverage",
  description:
    "Inspect the source, license, evidence limitations, immutable checksum, and coverage behind KFC Helper's WoW Forever preview.",
  path: "/forever/encyclopedia/sources/talents-forever",
  noIndex: true,
});

export default async function ForeverSourcePage(): Promise<React.JSX.Element> {
  try {
    const snapshot = await getForeverSnapshot();
    if (!snapshot) return <DataUnavailable title="The Forever source report is unavailable" />;
    const counts = snapshot.validation.counts;
    return (
      <article className="forever-source-page">
        <header className="forever-reference-hero">
          <Link className="helper-back-link" href="/forever/encyclopedia">
            <span aria-hidden="true">←</span> Forever Encyclopedia
          </Link>
          <span className="eyebrow">Provenance and audit</span>
          <h1>Talents Forever source</h1>
          <p>
            This page describes exactly what was imported, what remains uncertain, and how KFC
            Helper prevents a changing third-party feed from silently changing the public product.
          </p>
        </header>
        <section className="forever-source-metadata">
          <dl>
            <div>
              <dt>Snapshot checksum</dt>
              <dd>{snapshot.checksum}</dd>
            </div>
            <div>
              <dt>Source payload checksum</dt>
              <dd>{snapshot.sourcePayloadChecksum}</dd>
            </div>
            <div>
              <dt>Generated by source</dt>
              <dd>{snapshot.generated}</dd>
            </div>
            <div>
              <dt>Retrieved</dt>
              <dd>{snapshot.retrievedAt.toISOString()}</dd>
            </div>
            <div>
              <dt>Published by KFC Helper</dt>
              <dd>{snapshot.publishedAt.toISOString()}</dd>
            </div>
            <div>
              <dt>License</dt>
              <dd>
                <a
                  href={snapshot.source.licenseUrl}
                  rel="license noopener noreferrer"
                  target="_blank"
                >
                  {snapshot.source.license}
                </a>
              </dd>
            </div>
          </dl>
          <div>
            <h2>Validated coverage</h2>
            <ul>
              <li>{counts.classes} classes</li>
              <li>{counts.trees} talent trees</li>
              <li>{counts.talents} talents</li>
              <li>{counts.completeTalents} talents marked complete</li>
              <li>{counts.prerequisites} prerequisite relationships</li>
              <li>{counts.spellbookEntries} spellbook entries</li>
              <li>{counts.spellDescriptions} tooltip observations</li>
              <li>{counts.spellbookIcons} supplemental icon mappings</li>
            </ul>
          </div>
        </section>
        <section className="forever-source-limitations">
          <h2>Honest boundary</h2>
          <p>
            The source says its data was read from BlizzCon demo footage and Blizzard slides. It can
            lag the live game, many talent rank descriptions are incomplete, and most demo spell
            observations lack numeric client IDs. KFC Helper therefore stores this separately from
            client builds and never presents an estimate as client-verified data.
          </p>
          <p>
            <a href={snapshot.source.homepageUrl} rel="noopener noreferrer" target="_blank">
              Visit Talents Forever
            </a>{" "}
            ·{" "}
            <a href={snapshot.source.dataUrl} rel="noopener noreferrer" target="_blank">
              Inspect the original public export
            </a>{" "}
            ·{" "}
            <Link href="/api/v1/forever/preview.json">Use KFC Helper&apos;s versioned export</Link>
          </p>
        </section>
        <ForeverSnapshotNotice generated={snapshot.generated} checksum={snapshot.checksum} />
      </article>
    );
  } catch {
    return <DataUnavailable title="The Forever source report is temporarily unavailable" />;
  }
}
