import type { ChapterReference } from "./chapter-catalog.js";

// Header metadata only. Private guide prose and raw steps are never distributed.
export const CHAPTER_CATALOG_SOURCE = {
  version: 1,
  reviewedAt: "2026-10-04",
  guideCount: 157,
  sourceSha256: "af3fec7909e0b5a1dd8659f87e67171f8984af40a22b997e630a0052a11c871e",
  inventorySha256: "2c6d9f41faf2fd64ae7bb40a81476a655c53f7a1f4a4edee7cbb1ea3bb1a8637",
} as const;
export const CHAPTER_REFERENCES: readonly ChapterReference[] = [
  {
    id: "chapter-1-21-22-duskwood-mage-aoe",
    sourceId: 1,
    title: "21-22 Duskwood Mage AoE",
    factions: ["alliance"],
    family: "mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Alliance Mage"],
    labels: [],
    next: [{ value: "22-26 Wetlands Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-2-22-26-wetlands-mage-aoe",
    sourceId: 2,
    title: "22-26 Wetlands Mage AoE",
    factions: ["alliance"],
    family: "mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Alliance Mage"],
    labels: [],
    next: [{ value: "26-31 Duskwood Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-3-26-31-duskwood-part-2-mage-aoe",
    sourceId: 3,
    title: "26-31 Duskwood Part 2 Mage AoE",
    factions: ["alliance"],
    family: "mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Alliance Mage"],
    labels: [],
    next: [{ value: "31-33 Hillsbrad Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-4-31-33-hillsbrad-mage-aoe",
    sourceId: 4,
    title: "31-33 Hillsbrad Mage AoE",
    factions: ["alliance"],
    family: "mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Alliance Mage"],
    labels: [],
    next: [{ value: "33-60 Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-5-33-60-mage-aoe",
    sourceId: 5,
    title: "33-60 Mage AoE",
    factions: ["alliance"],
    family: "mage-aoe",
    condition: "Alliance Mage",
    defaults: [],
    labels: [],
    next: [],
    xpRates: [],
  },
  {
    id: "chapter-6-21-23-ashenvale-stonetalon",
    sourceId: 6,
    title: "21-23 Ashenvale/Stonetalon",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance Hunter",
    defaults: [],
    labels: [],
    next: [{ value: "23-24 Wetlands", condition: "" }],
    xpRates: [{ value: "<1.59", condition: "" }],
  },
  {
    id: "chapter-7-23-24-wetlands-hunter",
    sourceId: 7,
    title: "23-24 Wetlands Hunter",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance Hunter",
    defaults: [],
    labels: [{ value: "23-24 Wetlands", condition: "" }],
    next: [{ value: "24-27 Duskwood/Redridge", condition: "" }],
    xpRates: [{ value: "<1.59", condition: "" }],
  },
  {
    id: "chapter-8-21-23-stonetalon-ashenvale",
    sourceId: 8,
    title: "21-23 Stonetalon/Ashenvale",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance !Hunter",
    defaults: [],
    labels: [],
    next: [{ value: "23-24 Wetlands", condition: "" }],
    xpRates: [{ value: "<1.59", condition: "" }],
  },
  {
    id: "chapter-9-23-24-wetlands",
    sourceId: 9,
    title: "23-24 Wetlands",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance !Hunter",
    defaults: [],
    labels: [],
    next: [{ value: "24-27 Duskwood/Redridge", condition: "" }],
    xpRates: [{ value: "<1.59", condition: "" }],
  },
  {
    id: "chapter-10-24-27-duskwood-redridge",
    sourceId: 10,
    title: "24-27 Duskwood/Redridge",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [
      { value: "27-29 Wetlands/Hillsbrad", condition: "" },
      { value: "RestedXP Forever Guide (A)\\29-32 Duskwood", condition: "" },
    ],
    xpRates: [],
  },
  {
    id: "chapter-11-27-29-wetlands-hillsbrad",
    sourceId: 11,
    title: "27-29 Wetlands/Hillsbrad",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [
      { value: "RestedXP Forever Guide (A)\\29-32 Duskwood", condition: "Hunter" },
      { value: "29-30 Ashenvale", condition: "!Hunter" },
      { value: "RestedXP Forever Guide (A)\\29-32 Duskwood", condition: "!Hunter" },
    ],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-12-29-30-ashenvale",
    sourceId: 12,
    title: "29-30 Ashenvale",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance !Hunter",
    defaults: [],
    labels: [],
    next: [{ value: "RestedXP Forever Guide (A)\\29-32 Duskwood", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-13-29-32-duskwood",
    sourceId: 13,
    title: "29-32 Duskwood",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [{ value: "28-31 Duskwood II", condition: "sod" }],
    next: [{ value: "32-33 Hillsbrad/Arathi", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-14-32-33-hillsbrad-arathi",
    sourceId: 14,
    title: "32-33 Hillsbrad/Arathi",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [{ value: "31-33 Wetlands/Hillsbrad", condition: "sod" }],
    next: [{ value: "33-34 Thousand Needles", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-15-33-34-thousand-needles",
    sourceId: 15,
    title: "33-34 Thousand Needles",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "34-35 Stranglethorn Vale I", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-16-34-35-stranglethorn-vale-i",
    sourceId: 16,
    title: "34-35 Stranglethorn Vale I",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [
      { value: "35-36 Desolace", condition: "Hunter" },
      { value: "36-38 Stranglethorn Vale II", condition: "Hunter" },
      { value: "35-37 Desolace", condition: "!Hunter" },
      { value: "36-38 Stranglethorn Vale II", condition: "!Hunter" },
    ],
    xpRates: [],
  },
  {
    id: "chapter-17-35-36-desolace",
    sourceId: 17,
    title: "35-36 Desolace",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance Hunter",
    defaults: [],
    labels: [],
    next: [{ value: "36-38 Stranglethorn Vale II", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-18-35-37-desolace",
    sourceId: 18,
    title: "35-37 Desolace",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance !Hunter",
    defaults: [],
    labels: [],
    next: [{ value: "36-38 Stranglethorn Vale II", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-19-36-38-stranglethorn-vale-ii",
    sourceId: 19,
    title: "36-38 Stranglethorn Vale II",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "38-39 Swamp of Sorrows", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-20-38-39-swamp-of-sorrows",
    sourceId: 20,
    title: "38-39 Swamp of Sorrows",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "39-40 Alterac/Arathi", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-21-39-40-alterac-arathi",
    sourceId: 21,
    title: "39-40 Alterac/Arathi",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [
      { value: "RestedXP Forever Guide (A)\\40-40 Dustwallow Marsh", condition: "" },
      { value: "RestedXP Forever Guide (A)\\40-40 Dustwallow Marsh2", condition: "" },
    ],
    xpRates: [],
  },
  {
    id: "chapter-22-21-22-ashenvale-sod",
    sourceId: 22,
    title: "21-22 Ashenvale SoD",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [{ value: "21-22 Ashenvale", condition: "" }],
    next: [{ value: "22-24 Wetlands", condition: "" }],
    xpRates: [{ value: ">1.59", condition: "" }],
  },
  {
    id: "chapter-23-22-24-wetlands",
    sourceId: 23,
    title: "22-24 Wetlands",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [{ value: "22-24 Wetlands", condition: "SoD" }],
    next: [{ value: "24-27 Duskwood/Redridge", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-24-40-40-dustwallow-marsh2",
    sourceId: 24,
    title: "40-40 Dustwallow Marsh2",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance !Hunter",
    defaults: [],
    labels: [{ value: "40-40 Dustwallow Marsh", condition: "" }],
    next: [{ value: "40-41 Desolace", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-25-40-41-desolace",
    sourceId: 25,
    title: "40-41 Desolace",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance !Hunter",
    defaults: [],
    labels: [],
    next: [{ value: "41-41 Badlands", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-26-40-40-dustwallow-marsh",
    sourceId: 26,
    title: "40-40 Dustwallow Marsh",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "41-41 Badlands", condition: "" }],
    xpRates: [{ value: ">1.99", condition: "!Hunter" }],
  },
  {
    id: "chapter-27-41-41-badlands",
    sourceId: 27,
    title: "41-41 Badlands",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "41-43 STV/Swamp of Sorrows", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-28-41-43-stv-swamp-of-sorrows",
    sourceId: 28,
    title: "41-43 STV/Swamp of Sorrows",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [
      { value: "43-44 Tanaris", condition: "!Warlock" },
      { value: "43-44 Tanaris/Dustwallow", condition: "Warlock" },
    ],
    xpRates: [],
  },
  {
    id: "chapter-29-43-44-tanaris",
    sourceId: 29,
    title: "43-44 Tanaris",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance !Warlock",
    defaults: [],
    labels: [],
    next: [{ value: "44-48 Feralas", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-30-43-44-tanaris-dustwallow",
    sourceId: 30,
    title: "43-44 Tanaris/Dustwallow",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance Warlock",
    defaults: [],
    labels: [],
    next: [{ value: "44-48 Feralas", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-31-44-48-feralas",
    sourceId: 31,
    title: "44-48 Feralas",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "48-49 Tanaris/Hinterlands", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-32-48-49-tanaris-hinterlands",
    sourceId: 32,
    title: "48-49 Tanaris/Hinterlands",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "49-50 Tanaris/Un'Goro", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-33-49-50-tanaris-un-goro",
    sourceId: 33,
    title: "49-50 Tanaris/Un'Goro",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "RestedXP Forever Guide (A)\\50-50 Stranglethorn Vale", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-34-50-50-stranglethorn-vale",
    sourceId: 34,
    title: "50-50 Stranglethorn Vale",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "50-51 Searing Gorge", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-35-50-51-searing-gorge",
    sourceId: 35,
    title: "50-51 Searing Gorge",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "51-51 Blasted Lands", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-36-51-51-blasted-lands",
    sourceId: 36,
    title: "51-51 Blasted Lands",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "51-52 WPL", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-37-51-52-wpl",
    sourceId: 37,
    title: "51-52 WPL",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "52-52 Felwood", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-38-52-52-felwood",
    sourceId: 38,
    title: "52-52 Felwood",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "52-53 Feralas", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-39-52-53-feralas",
    sourceId: 39,
    title: "52-53 Feralas",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "53-53 Azshara", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-40-53-53-azshara",
    sourceId: 40,
    title: "53-53 Azshara",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "53-54 UnGoro Crater", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-41-53-54-ungoro-crater",
    sourceId: 41,
    title: "53-54 UnGoro Crater",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "54-55 Felwood/Winterspring", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-42-54-55-felwood-winterspring",
    sourceId: 42,
    title: "54-55 Felwood/Winterspring",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "55-56 Winterspring", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-43-55-56-winterspring",
    sourceId: 43,
    title: "55-56 Winterspring",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "56-57 Burning Steppes", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-44-56-57-burning-steppes",
    sourceId: 44,
    title: "56-57 Burning Steppes",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "57-59 Western/Eastern Plaguelands", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-45-57-59-western-eastern-plaguelands",
    sourceId: 45,
    title: "57-59 Western/Eastern Plaguelands",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "59-59 Winterspring/Silithus part 1", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-46-59-59-winterspring-silithus-part-1",
    sourceId: 46,
    title: "59-59 Winterspring/Silithus part 1",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [{ value: "59-60 Winterspring/Silithus part 2", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-47-59-60-winterspring-silithus-part-2",
    sourceId: 47,
    title: "59-60 Winterspring/Silithus part 2",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [],
    xpRates: [],
  },
  {
    id: "chapter-48-21-30-silverpine-hillsbrad-aoe",
    sourceId: 48,
    title: "21-30 Silverpine/Hillsbrad AoE",
    factions: ["horde"],
    family: "mage-aoe",
    condition: "Horde Mage",
    defaults: ["Horde Mage"],
    labels: [],
    next: [{ value: "30-36 Arathi/Alterac AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-49-30-36-arathi-alterac-aoe",
    sourceId: 49,
    title: "30-36 Arathi/Alterac AoE",
    factions: ["horde"],
    family: "mage-aoe",
    condition: "Horde Mage",
    defaults: ["Horde Mage"],
    labels: [],
    next: [{ value: "36-60 Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-50-36-60-mage-aoe",
    sourceId: 50,
    title: "36-60 Mage AoE",
    factions: ["horde"],
    family: "mage-aoe",
    condition: "Horde Mage",
    defaults: [],
    labels: [],
    next: [],
    xpRates: [],
  },
  {
    id: "chapter-51-23-24-hillsbrad-class-quests",
    sourceId: 51,
    title: "23-24 Hillsbrad Class Quests",
    factions: ["horde"],
    family: "questing",
    condition: "Horde Shaman/Horde Rogue",
    defaults: [],
    labels: [],
    next: [{ value: "24-26 Southern Barrens", condition: "" }],
    xpRates: [{ value: ">1.99", condition: "" }],
  },
  {
    id: "chapter-52-22-24-hillsbrad",
    sourceId: 52,
    title: "22-24 Hillsbrad",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [],
    next: [{ value: "24-26 Southern Barrens/Stonetalon", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-53-24-26-southern-barrens-stonetalon",
    sourceId: 53,
    title: "24-26 Southern Barrens/Stonetalon",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [],
    next: [{ value: "26-28 Ashenvale", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-54-24-26-southern-barrens",
    sourceId: 54,
    title: "24-26 Southern Barrens",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [],
    next: [
      { value: "26-28 Ashenvale", condition: "" },
      { value: "26-28 SoD Ashenvale", condition: "" },
    ],
    xpRates: [{ value: ">1.99", condition: "" }],
  },
  {
    id: "chapter-55-26-28-ashenvale",
    sourceId: 55,
    title: "26-28 Ashenvale",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [],
    next: [{ value: "28-30 Thousand Needles", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-56-26-28-sod-ashenvale",
    sourceId: 56,
    title: "26-28 SoD Ashenvale",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "26-28 Ashenvale", condition: "" }],
    next: [{ value: "28-30 Thousand Needles", condition: "" }],
    xpRates: [{ value: ">1.99", condition: "" }],
  },
  {
    id: "chapter-57-28-30-thousand-needles",
    sourceId: 57,
    title: "28-30 Thousand Needles",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "28-33 Thousand Needles", condition: "sod" }],
    next: [
      { value: "RestedXP Forever Guide (H)\\30-33 Hillsbrad/Arathi", condition: "" },
      { value: "RestedXP Forever Guide (H)\\33-34 Shimmering Flats", condition: "" },
    ],
    xpRates: [],
  },
  {
    id: "chapter-58-30-33-hillsbrad-arathi",
    sourceId: 58,
    title: "30-33 Hillsbrad/Arathi",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [],
    next: [{ value: "33-34 Shimmering Flats", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-59-33-34-shimmering-flats",
    sourceId: 59,
    title: "33-34 Shimmering Flats",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "33-35 Shimmering Flats", condition: "sod" }],
    next: [
      { value: "RestedXP Forever Guide (H)\\34-35 Desolace", condition: "" },
      { value: "RestedXP Forever Guide (H)\\35-37 Northern Stranglethorn", condition: "" },
    ],
    xpRates: [],
  },
  {
    id: "chapter-60-34-35-desolace",
    sourceId: 60,
    title: "34-35 Desolace",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "34-36 Desolace", condition: "sod" }],
    next: [{ value: "35-37 Northern Stranglethorn", condition: "" }],
    xpRates: [{ value: "<2.1", condition: "" }],
  },
  {
    id: "chapter-61-35-37-northern-stranglethorn",
    sourceId: 61,
    title: "35-37 Northern Stranglethorn",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "35-38 Northern Stranglethorn", condition: "sod" }],
    next: [{ value: "37-38 Dustwallow Marsh", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-62-37-38-dustwallow-marsh",
    sourceId: 62,
    title: "37-38 Dustwallow Marsh",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "38-40 Dustwallow Marsh", condition: "sod" }],
    next: [
      { value: "RestedXP Forever Guide (H)\\38-39 Alterac/Arathi", condition: "" },
      { value: "RestedXP Forever Guide (H)\\40-41 Stranglethorn Vale", condition: "" },
    ],
    xpRates: [],
  },
  {
    id: "chapter-63-38-39-alterac-arathi",
    sourceId: 63,
    title: "38-39 Alterac/Arathi",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [],
    next: [{ value: "39-40 Badlands", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-64-39-40-badlands",
    sourceId: 64,
    title: "39-40 Badlands",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [],
    next: [{ value: "RestedXP Forever Guide (H)\\40-41 Stranglethorn Vale", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-65-40-41-stranglethorn-vale",
    sourceId: 65,
    title: "40-41 Stranglethorn Vale",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [],
    next: [{ value: "41-400_41-41 Swamp of Sorrows", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-66-41-400-41-41-swamp-of-sorrows",
    sourceId: 66,
    title: "41-400_41-41 Swamp of Sorrows",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [
      { value: "41-41 Swamp of Sorrows", condition: "!sod" },
      { value: "41-42 Swamp of Sorrows", condition: "sod" },
    ],
    next: [
      { value: "RestedXP Forever Guide (H)\\41-41 Desolace II", condition: "" },
      { value: "RestedXP Forever Guide (H)\\41-43 Tanaris/Dustwallow", condition: "" },
    ],
    xpRates: [],
  },
  {
    id: "chapter-67-41-41-desolace-ii",
    sourceId: 67,
    title: "41-41 Desolace II",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [],
    next: [{ value: "41-43 Tanaris/Dustwallow", condition: "" }],
    xpRates: [{ value: "<1.5", condition: "" }],
  },
  {
    id: "chapter-68-41-43-tanaris-dustwallow",
    sourceId: 68,
    title: "41-43 Tanaris/Dustwallow",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "42-44 Tanaris/Dustwallow", condition: "sod" }],
    next: [{ value: "43-44 Feralas", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-69-43-44-feralas",
    sourceId: 69,
    title: "43-44 Feralas",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "44-48 Feralas", condition: "sod" }],
    next: [
      { value: "44-45 Southern Stranglethorn", condition: "" },
      { value: "46-48 Tanaris", condition: "" },
    ],
    xpRates: [],
  },
  {
    id: "chapter-70-44-45-southern-stranglethorn",
    sourceId: 70,
    title: "44-45 Southern Stranglethorn",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "46-47 Southern Stranglethorn", condition: "sod" }],
    next: [
      { value: "45-46 Swamp of Sorrows", condition: "" },
      { value: "46-48 Tanaris", condition: "" },
    ],
    xpRates: [{ value: "<2.1", condition: "" }],
  },
  {
    id: "chapter-71-45-46-swamp-of-sorrows",
    sourceId: 71,
    title: "45-46 Swamp of Sorrows",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "47-47 Swamp of Sorrows", condition: "SoD" }],
    next: [{ value: "46-48 Tanaris", condition: "" }],
    xpRates: [{ value: "<2.1", condition: "" }],
  },
  {
    id: "chapter-72-46-48-tanaris",
    sourceId: 72,
    title: "46-48 Tanaris",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "48-50 Tanaris", condition: "sod" }],
    next: [{ value: "48-49 The Hinterlands", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-73-48-49-the-hinterlands",
    sourceId: 73,
    title: "48-49 The Hinterlands",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "50-52 The Hinterlands", condition: "Sod" }],
    next: [{ value: "49-50 Feralas", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-74-49-50-feralas",
    sourceId: 74,
    title: "49-50 Feralas",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "52-53 Un'Goro Crater", condition: "sod" }],
    next: [
      { value: "RestedXP Forever Guide (H)\\50-51 Stranglethorn/Blasted Lands", condition: "" },
      { value: "RestedXP Forever Guide (H)\\51-52 Searing Gorge/Burning Steppes", condition: "" },
      { value: "RestedXP Forever Guide (H)\\52-53 Azshara", condition: "" },
    ],
    xpRates: [],
  },
  {
    id: "chapter-75-50-51-stranglethorn-blasted-lands",
    sourceId: 75,
    title: "50-51 Stranglethorn/Blasted Lands",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [],
    next: [{ value: "51-52 Searing Gorge/Burning Steppes", condition: "" }],
    xpRates: [{ value: "<1.5", condition: "" }],
  },
  {
    id: "chapter-76-51-52-searing-gorge-burning-steppes",
    sourceId: 76,
    title: "51-52 Searing Gorge/Burning Steppes",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [],
    next: [{ value: "52-53 Azshara", condition: "" }],
    xpRates: [{ value: "<2.0", condition: "" }],
  },
  {
    id: "chapter-77-52-53-azshara",
    sourceId: 77,
    title: "52-53 Azshara",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "53-54 Azshara", condition: "sod" }],
    next: [{ value: "53-54 Felwood", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-78-53-54-felwood",
    sourceId: 78,
    title: "53-54 Felwood",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "54-54 Felwood", condition: "sod" }],
    next: [{ value: "54-55 Un'Goro Crater", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-79-54-55-un-goro-crater",
    sourceId: 79,
    title: "54-55 Un'Goro Crater",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "54-56 Un'Goro Crater", condition: "sod" }],
    next: [{ value: "55-56 Felwood/Winterspring", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-80-55-56-felwood-winterspring",
    sourceId: 80,
    title: "55-56 Felwood/Winterspring",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "56-57 Felwood/Winterspring", condition: "sod" }],
    next: [{ value: "56-58 Western PL/Eastern PL", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-81-56-58-western-pl-eastern-pl",
    sourceId: 81,
    title: "56-58 Western PL/Eastern PL",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [{ value: "57-59 Western PL/Eastern PL", condition: "sod" }],
    next: [{ value: "58-59 Winterspring/Silithus I", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-82-58-59-winterspring-silithus-i",
    sourceId: 82,
    title: "58-59 Winterspring/Silithus I",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [],
    next: [{ value: "59-60 Winterspring/Silithus II", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-83-59-60-winterspring-silithus-ii",
    sourceId: 83,
    title: "59-60 Winterspring/Silithus II",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [],
    next: [],
    xpRates: [],
  },
  {
    id: "chapter-84-1-10-adv-elwynn-forest-human-mage-aoe",
    sourceId: 84,
    title: "1-10 ADV Elwynn Forest Human Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Human Mage",
    defaults: ["Human Mage"],
    labels: [],
    next: [{ value: "10-11 ADV Dun Morogh Human Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-85-10-11-adv-dun-morogh-human-mage-aoe",
    sourceId: 85,
    title: "10-11 ADV Dun Morogh Human Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Human Mage",
    defaults: ["Human Mage"],
    labels: [],
    next: [{ value: "10-12 ADV Darkshore 1 Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-86-1-10-adv-dun-morogh-gnome-mage-aoe",
    sourceId: 86,
    title: "1-10 ADV Dun Morogh Gnome Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Gnome Mage",
    defaults: ["Gnome Mage"],
    labels: [],
    next: [{ value: "10-12 ADV Darkshore 1 Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-87-10-12-adv-darkshore-1-mage-aoe",
    sourceId: 87,
    title: "10-12 ADV Darkshore 1 Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Human Mage/Gnome Mage"],
    labels: [],
    next: [{ value: "12-14 ADV Loch Modan Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-88-10-12-launch-adv-darkshore-1-mage-aoe",
    sourceId: 88,
    title: "10-12 LAUNCH ADV Darkshore 1 Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: ["none"],
    labels: [],
    next: [{ value: "12-14 ADV Loch Modan Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-89-12-14-adv-loch-modan-mage-aoe",
    sourceId: 89,
    title: "12-14 ADV Loch Modan Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Human Mage/Gnome Mage"],
    labels: [],
    next: [{ value: "14-16 ADV Darkshore 2 Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-90-14-16-adv-darkshore-2-mage-aoe",
    sourceId: 90,
    title: "14-16 ADV Darkshore 2 Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Human Mage/Gnome Mage"],
    labels: [],
    next: [{ value: "16-18 ADV Westfall Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-91-16-18-adv-westfall-mage-aoe",
    sourceId: 91,
    title: "16-18 ADV Westfall Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Human Mage/Gnome Mage"],
    labels: [],
    next: [{ value: "18-20 ADV Darkshore 3 Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-92-18-20-adv-darkshore-3-mage-aoe",
    sourceId: 92,
    title: "18-20 ADV Darkshore 3 Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Human Mage/Gnome Mage"],
    labels: [],
    next: [{ value: "20-22 ADV Redridge 1 Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-93-20-22-adv-redridge-1-mage-aoe",
    sourceId: 93,
    title: "20-22 ADV Redridge 1 Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Human Mage/Gnome Mage"],
    labels: [],
    next: [{ value: "22-26 ADV Wetlands 1 Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-94-1-10-elwynn-forest-mage-aoe",
    sourceId: 94,
    title: "1-10 Elwynn Forest Mage AoE",
    factions: ["alliance"],
    family: "mage-aoe",
    condition: "Human Mage",
    defaults: ["Human"],
    labels: [],
    next: [{ value: "10-12 Loch Modan Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-95-1-10-dun-morogh-mage-aoe",
    sourceId: 95,
    title: "1-10 Dun Morogh Mage AoE",
    factions: ["alliance"],
    family: "mage-aoe",
    condition: "Gnome Mage",
    defaults: ["Dwarf/Gnome"],
    labels: [],
    next: [{ value: "10-12 Loch Modan Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-96-10-12-loch-modan-mage-aoe",
    sourceId: 96,
    title: "10-12 Loch Modan Mage AoE",
    factions: ["alliance"],
    family: "mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Human Mage/Gnome Mage"],
    labels: [],
    next: [{ value: "12-18 Darkshore Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-97-12-18-darkshore-mage-aoe",
    sourceId: 97,
    title: "12-18 Darkshore Mage AoE",
    factions: ["alliance"],
    family: "mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Alliance Mage"],
    labels: [],
    next: [{ value: "18-21 Redridge Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-98-18-21-redridge-mage-aoe",
    sourceId: 98,
    title: "18-21 Redridge Mage AoE",
    factions: ["alliance"],
    family: "mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Alliance Mage"],
    labels: [],
    next: [{ value: "21-22 Duskwood Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-99-12-17-the-barrens-aoe",
    sourceId: 99,
    title: "12-17 The Barrens AoE",
    factions: ["horde"],
    family: "mage-aoe",
    condition: "Horde Mage",
    defaults: ["Horde Mage"],
    labels: [],
    next: [{ value: "17-21 Stonetalon/Barrens AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-100-17-21-stonetalon-barrens-aoe",
    sourceId: 100,
    title: "17-21 Stonetalon/Barrens AoE",
    factions: ["horde"],
    family: "mage-aoe",
    condition: "Horde Mage",
    defaults: ["Horde Mage"],
    labels: [],
    next: [{ value: "21-30 Silverpine/Hillsbrad AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-101-22-26-adv-wetlands-1-mage-aoe",
    sourceId: 101,
    title: "22-26 ADV Wetlands 1 Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Alliance Mage"],
    labels: [],
    next: [{ value: "26-27 ADV Redridge 2 Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-102-26-27-adv-redridge-2-mage-aoe",
    sourceId: 102,
    title: "26-27 ADV Redridge 2 Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Alliance Mage"],
    labels: [],
    next: [{ value: "27-32 ADV Duskwood Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-103-27-32-adv-duskwood-mage-aoe",
    sourceId: 103,
    title: "27-32 ADV Duskwood Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Alliance Mage"],
    labels: [],
    next: [{ value: "32-33 ADV Hillsbrad Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-104-32-33-adv-hillsbrad-mage-aoe",
    sourceId: 104,
    title: "32-33 ADV Hillsbrad Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Alliance Mage"],
    labels: [],
    next: [{ value: "33-37 ADV Arathi Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-105-33-37-adv-arathi-mage-aoe",
    sourceId: 105,
    title: "33-37 ADV Arathi Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: [],
    labels: [],
    next: [{ value: "37-41 ADV Dustwallow Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-106-37-41-adv-dustwallow-mage-aoe",
    sourceId: 106,
    title: "37-41 ADV Dustwallow Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: [],
    labels: [],
    next: [{ value: "41-41 ADV Dustwallow/Alterac Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-107-41-41-adv-dustwallow-alterac-mage-aoe",
    sourceId: 107,
    title: "41-41 ADV Dustwallow/Alterac Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: [],
    labels: [],
    next: [{ value: "41-42 ADV Badlands Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-108-41-42-adv-badlands-mage-aoe",
    sourceId: 108,
    title: "41-42 ADV Badlands Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: [],
    labels: [],
    next: [{ value: "42-50 ADV Tanaris Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-109-42-50-adv-tanaris-mage-aoe",
    sourceId: 109,
    title: "42-50 ADV Tanaris Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: [],
    labels: [],
    next: [{ value: "50-51 ADV Searing Gorge Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-110-50-51-adv-searing-gorge-mage-aoe",
    sourceId: 110,
    title: "50-51 ADV Searing Gorge Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: [],
    labels: [],
    next: [{ value: "51-52 ADV Tanaris/Un'Goro Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-111-51-52-adv-tanaris-un-goro-mage-aoe",
    sourceId: 111,
    title: "51-52 ADV Tanaris/Un'Goro Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Alliance Mage"],
    labels: [],
    next: [{ value: "52-60 ADV Plaguelands Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-112-52-60-adv-plaguelands-mage-aoe",
    sourceId: 112,
    title: "52-60 ADV Plaguelands Mage AoE",
    factions: ["alliance"],
    family: "advanced-mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Alliance Mage"],
    labels: [],
    next: [],
    xpRates: [],
  },
  {
    id: "chapter-113-1-6-shadowglen",
    sourceId: 113,
    title: "1-6 Shadowglen",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: ["NightElf"],
    labels: [{ value: "1-7 Shadowglen", condition: "sod" }],
    next: [{ value: "6-11 Teldrassil", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-114-6-11-teldrassil",
    sourceId: 114,
    title: "6-11 Teldrassil",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: ["NightElf"],
    labels: [{ value: "7-13 Teldrassil", condition: "SoD" }],
    next: [{ value: "14-16 Darkshore", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-115-1-6-northshire",
    sourceId: 115,
    title: "1-6 Northshire",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: ["Human"],
    labels: [],
    next: [{ value: "6-11 Elwynn Forest", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-116-6-11-elwynn-forest",
    sourceId: 116,
    title: "6-11 Elwynn Forest",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: ["Human"],
    labels: [{ value: "6-13 Elwynn Forest", condition: "SoD" }],
    next: [{ value: "11-13 Loch Modan", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-117-11-13-loch-modan",
    sourceId: 117,
    title: "11-13 Loch Modan",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: ["Human"],
    labels: [{ value: "13-15 Loch Modan", condition: "SoD" }],
    next: [
      { value: "13-15 Westfall", condition: "" },
      { value: "14-16 Darkshore", condition: "" },
    ],
    xpRates: [],
  },
  {
    id: "chapter-118-1-6-coldridge-valley",
    sourceId: 118,
    title: "1-6 Coldridge Valley",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: ["Dwarf/Gnome"],
    labels: [
      { value: "1-6 Coldridge Valley", condition: "!SoD" },
      { value: "1-7 Coldridge Valley", condition: "SoD" },
    ],
    next: [
      { value: "6-11 Dun Morogh", condition: "!Hunter" },
      { value: "6-11 Dun Morogh (Hunter)", condition: "Hunter" },
      { value: "6-11 Dun Morogh", condition: "Hunter" },
    ],
    xpRates: [],
  },
  {
    id: "chapter-119-6-11-dun-morogh",
    sourceId: 119,
    title: "6-11 Dun Morogh",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance --!Hunter",
    defaults: ["Dwarf/Gnome"],
    labels: [{ value: "6-12 Dun Morogh", condition: "sod !Warlock" }],
    next: [
      { value: "11-12 Elwynn (Dwarf/Gnome)", condition: "" },
      { value: "11-12 Voidwalker Quest", condition: "" },
      { value: "12-14 Loch Modan (Dwarf/Gnome)", condition: "" },
      { value: "11-13 Loch Modan (Hunter)", condition: "" },
    ],
    xpRates: [{ value: ">1.49", condition: "Hunter" }],
  },
  {
    id: "chapter-120-11-12-voidwalker-quest",
    sourceId: 120,
    title: "11-12 Voidwalker Quest",
    factions: ["alliance"],
    family: "questing",
    condition: "Gnome Warlock",
    defaults: [],
    labels: [{ value: "12-13 Voidwalker Quest", condition: "SoD" }],
    next: [{ value: "12-14 Loch Modan (Dwarf/Gnome)", condition: "" }],
    xpRates: [{ value: ">1.49", condition: "" }],
  },
  {
    id: "chapter-121-11-12-elwynn-dwarf-gnome",
    sourceId: 121,
    title: "11-12 Elwynn (Dwarf/Gnome)",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance !Hunter",
    defaults: ["Gnome/Dwarf"],
    labels: [],
    next: [{ value: "12-14 Loch Modan (Dwarf/Gnome)", condition: "" }],
    xpRates: [{ value: "<1.5", condition: "" }],
  },
  {
    id: "chapter-122-12-14-loch-modan-dwarf-gnome",
    sourceId: 122,
    title: "12-14 Loch Modan (Dwarf/Gnome)",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance !Hunter",
    defaults: ["Gnome/Dwarf"],
    labels: [
      { value: "12-15 Loch Modan", condition: "SoD !Warlock" },
      { value: "13-15 Loch Modan", condition: "SoD Warlock" },
    ],
    next: [
      { value: "13-15 Westfall", condition: "" },
      { value: "14-16 Darkshore", condition: "" },
    ],
    xpRates: [],
  },
  {
    id: "chapter-123-6-11-dun-morogh-hunter",
    sourceId: 123,
    title: "6-11 Dun Morogh (Hunter)",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance Hunter",
    defaults: ["Dwarf Hunter"],
    labels: [{ value: "6-11 Dun Morogh", condition: "" }],
    next: [{ value: "11-13 Loch Modan (Hunter)", condition: "" }],
    xpRates: [{ value: "<1.5", condition: "" }],
  },
  {
    id: "chapter-124-11-13-loch-modan-hunter",
    sourceId: 124,
    title: "11-13 Loch Modan (Hunter)",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance Hunter",
    defaults: ["Dwarf"],
    labels: [
      { value: "11-13 Loch Modan", condition: "!SoD" },
      { value: "12-15 Loch Modan", condition: "SoD" },
    ],
    next: [{ value: "14-16 Darkshore", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-125-13-15-westfall",
    sourceId: 125,
    title: "13-15 Westfall",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: ["!NightElf !Hunter"],
    labels: [{ value: "14-15 Westfall", condition: "Dwarf/Gnome" }],
    next: [{ value: "14-16 Darkshore", condition: "" }],
    xpRates: [{ value: "<1.5", condition: "" }],
  },
  {
    id: "chapter-126-14-16-darkshore",
    sourceId: 126,
    title: "14-16 Darkshore",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [
      { value: "11-16 Darkshore", condition: "NightElf" },
      { value: "13-16 Darkshore", condition: "Dwarf Hunter" },
      { value: "15-16 Darkshore", condition: "!NightElf/!Dwarf Hunter" },
    ],
    next: [{ value: "16-19 Darkshore", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-127-16-19-darkshore",
    sourceId: 127,
    title: "16-19 Darkshore",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance",
    defaults: [],
    labels: [],
    next: [
      { value: "19-20 Redridge", condition: "!Hunter" },
      { value: "20-21 Darkshore/Ashenvale", condition: "!Hunter" },
      { value: "19-21 Darkshore/Ashenvale", condition: "Hunter" },
    ],
    xpRates: [],
  },
  {
    id: "chapter-128-19-20-redridge",
    sourceId: 128,
    title: "19-20 Redridge",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance !Hunter",
    defaults: [],
    labels: [],
    next: [{ value: "20-21 Darkshore/Ashenvale", condition: "" }],
    xpRates: [{ value: "<1.59", condition: "" }],
  },
  {
    id: "chapter-129-19-21-darkshore-ashenvale",
    sourceId: 129,
    title: "19-21 Darkshore/Ashenvale",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance Hunter",
    defaults: [],
    labels: [],
    next: [{ value: "RestedXP Forever Guide (A)\\21-23 Ashenvale/Stonetalon", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-130-20-21-darkshore-ashenvale",
    sourceId: 130,
    title: "20-21 Darkshore/Ashenvale",
    factions: ["alliance"],
    family: "questing",
    condition: "Alliance !Hunter",
    defaults: [],
    labels: [],
    next: [
      { value: "RestedXP Forever Guide (A)\\21-23 Stonetalon/Ashenvale", condition: "" },
      { value: "RestedXP Forever Guide (A)\\21-22 Ashenvale SoD", condition: "" },
    ],
    xpRates: [],
  },
  {
    id: "chapter-131-1-10-elwynn-forest-mage-aoe",
    sourceId: 131,
    title: "1-10 Elwynn Forest Mage AoE",
    factions: ["alliance"],
    family: "mage-aoe",
    condition: "Human Mage",
    defaults: ["Human"],
    labels: [],
    next: [{ value: "10-12 Loch Modan Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-132-1-10-dun-morogh-mage-aoe",
    sourceId: 132,
    title: "1-10 Dun Morogh Mage AoE",
    factions: ["alliance"],
    family: "mage-aoe",
    condition: "Gnome Mage",
    defaults: ["Dwarf/Gnome"],
    labels: [],
    next: [{ value: "10-12 Loch Modan Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-133-10-12-loch-modan-mage-aoe",
    sourceId: 133,
    title: "10-12 Loch Modan Mage AoE",
    factions: ["alliance"],
    family: "mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Human Mage/Gnome Mage"],
    labels: [],
    next: [{ value: "12-18 Darkshore Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-134-12-18-darkshore-mage-aoe",
    sourceId: 134,
    title: "12-18 Darkshore Mage AoE",
    factions: ["alliance"],
    family: "mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Alliance Mage"],
    labels: [],
    next: [{ value: "18-21 Redridge Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-135-18-21-redridge-mage-aoe",
    sourceId: 135,
    title: "18-21 Redridge Mage AoE",
    factions: ["alliance"],
    family: "mage-aoe",
    condition: "Alliance Mage",
    defaults: ["Alliance Mage"],
    labels: [],
    next: [{ value: "21-22 Duskwood Mage AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-136-1-6-durotar",
    sourceId: 136,
    title: "1-6 Durotar",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: ["Troll/Orc"],
    labels: [],
    next: [{ value: "6-10 Durotar", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-137-6-10-durotar",
    sourceId: 137,
    title: "6-10 Durotar",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: ["Troll/Orc"],
    labels: [],
    next: [{ value: "10-12 Durotar", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-138-10-12-durotar",
    sourceId: 138,
    title: "10-12 Durotar",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: ["Troll/Orc"],
    labels: [],
    next: [
      {
        value: "10-12 Tirisfal",
        condition: "Troll Rogue/Orc Rogue/Orc Warlock/Troll Mage/Troll Priest",
      },
      { value: "12-17 The Barrens", condition: "Troll !Rogue !Mage !Priest/Orc !Rogue !Warlock" },
    ],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-139-10-12-tirisfal",
    sourceId: 139,
    title: "10-12 Tirisfal",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: ["Troll Rogue/Orc Rogue/Orc Warlock/Troll Mage/Troll Priest"],
    labels: [],
    next: [
      {
        value: "12-14 Silverpine Forest",
        condition: "Undead/Troll Rogue/Orc Rogue/Orc Warlock/Troll Mage/Troll Priest",
      },
    ],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-140-1-7-durotar",
    sourceId: 140,
    title: "1-7 Durotar",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: ["Troll/Orc"],
    labels: [],
    next: [{ value: "7-13 Durotar", condition: "" }],
    xpRates: [{ value: ">1.99", condition: "" }],
  },
  {
    id: "chapter-141-7-13-durotar",
    sourceId: 141,
    title: "7-13 Durotar",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: ["Troll/Orc"],
    labels: [],
    next: [{ value: "13-20 The Barrens", condition: "" }],
    xpRates: [{ value: ">1.99", condition: "" }],
  },
  {
    id: "chapter-142-1-6-tirisfal-glades",
    sourceId: 142,
    title: "1-6 Tirisfal Glades",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: ["Undead"],
    labels: [],
    next: [{ value: "6-11 Tirisfal Glades", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-143-6-11-tirisfal-glades",
    sourceId: 143,
    title: "6-11 Tirisfal Glades",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: ["Undead"],
    labels: [],
    next: [
      { value: "12-14 Silverpine Forest", condition: "" },
      { value: "12-17 The Barrens", condition: "" },
    ],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-144-12-14-silverpine-forest",
    sourceId: 144,
    title: "12-14 Silverpine Forest",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: ["Undead/Troll Rogue/Orc Rogue/Orc Warlock/Troll Mage/Troll Priest"],
    labels: [],
    next: [{ value: "12-17 The Barrens", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-145-1-7-tirisfal-glades",
    sourceId: 145,
    title: "1-7 Tirisfal Glades",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: ["Undead"],
    labels: [],
    next: [{ value: "7-13 Tirisfal Glades", condition: "" }],
    xpRates: [{ value: ">1.99", condition: "" }],
  },
  {
    id: "chapter-146-7-13-tirisfal-glades",
    sourceId: 146,
    title: "7-13 Tirisfal Glades",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: ["Undead"],
    labels: [],
    next: [{ value: "13-20 The Barrens", condition: "" }],
    xpRates: [{ value: ">1.99", condition: "" }],
  },
  {
    id: "chapter-147-1-6-mulgore",
    sourceId: 147,
    title: "1-6 Mulgore",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: ["Tauren"],
    labels: [],
    next: [
      { value: "6-12 Mulgore", condition: "" },
      { value: "6-13 Mulgore", condition: "" },
    ],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-148-6-12-mulgore",
    sourceId: 148,
    title: "6-12 Mulgore",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: ["Tauren"],
    labels: [],
    next: [{ value: "12-17 The Barrens", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-149-1-7-mulgore",
    sourceId: 149,
    title: "1-7 Mulgore",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: ["Tauren"],
    labels: [],
    next: [{ value: "7-13 Mulgore", condition: "" }],
    xpRates: [{ value: ">1.99", condition: "" }],
  },
  {
    id: "chapter-150-7-13-mulgore",
    sourceId: 150,
    title: "7-13 Mulgore",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: ["Tauren"],
    labels: [],
    next: [{ value: "13-20 The Barrens", condition: "" }],
    xpRates: [{ value: ">1.99", condition: "" }],
  },
  {
    id: "chapter-151-12-17-the-barrens",
    sourceId: 151,
    title: "12-17 The Barrens",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [
      {
        value: "14-18 The Barrens",
        condition: "Undead/Troll Rogue/Orc Rogue/Orc Warlock/Troll Mage/Troll Priest",
      },
    ],
    next: [{ value: "17-22 Stonetalon/Barrens/Ashenvale", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-152-17-22-stonetalon-barrens-ashenvale",
    sourceId: 152,
    title: "17-22 Stonetalon/Barrens/Ashenvale",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [
      {
        value: "18-22 Stonetalon/Barrens/Ashenvale",
        condition: "Undead/Troll Rogue/Orc Rogue/Orc Warlock/Troll Mage/Troll Priest",
      },
    ],
    next: [{ value: "RestedXP Forever Guide (H)\\22-24 Hillsbrad", condition: "" }],
    xpRates: [{ value: "<1.99", condition: "" }],
  },
  {
    id: "chapter-153-13-20-the-barrens",
    sourceId: 153,
    title: "13-20 The Barrens",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [],
    next: [{ value: "20-24 Stonetalon/Barrens", condition: "" }],
    xpRates: [{ value: ">1.99", condition: "" }],
  },
  {
    id: "chapter-154-20-24-stonetalon-barrens",
    sourceId: 154,
    title: "20-24 Stonetalon/Barrens",
    factions: ["horde"],
    family: "questing",
    condition: "Horde",
    defaults: [],
    labels: [],
    next: [
      { value: "24-26 Southern Barrens", condition: "!Rogue !Shaman" },
      { value: "23-24 Hillsbrad Class Quests", condition: "Rogue/Shaman" },
    ],
    xpRates: [{ value: ">1.99", condition: "" }],
  },
  {
    id: "chapter-155-12-17-the-barrens-aoe",
    sourceId: 155,
    title: "12-17 The Barrens AoE",
    factions: ["horde"],
    family: "mage-aoe",
    condition: "Horde Mage",
    defaults: ["Horde Mage"],
    labels: [],
    next: [{ value: "17-21 Stonetalon/Barrens AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-156-17-21-stonetalon-barrens-aoe",
    sourceId: 156,
    title: "17-21 Stonetalon/Barrens AoE",
    factions: ["horde"],
    family: "mage-aoe",
    condition: "Horde Mage",
    defaults: ["Horde Mage"],
    labels: [],
    next: [{ value: "21-30 Silverpine/Hillsbrad AoE", condition: "" }],
    xpRates: [],
  },
  {
    id: "chapter-157-1-14-zephras-isle",
    sourceId: 157,
    title: "1-14 Zephras Isle",
    factions: ["alliance", "horde"],
    family: "questing",
    condition: "",
    defaults: ["Skyborne"],
    labels: [
      { value: "1-13 Skyborne", condition: "Alliance" },
      { value: "1-12 Skyborne", condition: "Horde" },
    ],
    next: [{ value: "13-15 Westfall", condition: "Alliance" }],
    xpRates: [],
  },
];
